//Modal
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

//Tooltip
export const SHOW_TOOLTIP = 'SHOW_TOOLTIP'
export const HIDE_TOOLTIP = 'HIDE_TOOLTIP'

//Account
export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT'
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT'


//Character
export const GET_CHARACTERS = 'GET_CHARACTERS'
export const UPDATE_CHARACTER = 'UPDATE_CHARACTER'
export const SET_LOGGED_IN_CHARACTER = 'SET_LOGGED_IN_CHARACTER'
export const GET_INVENTORY = 'GET_INVENTORY'
export const GET_EQUIPMENT = 'GET_EQUIPMENT'
export const EQUIP_ITEM_FROM_INVENTORY = 'EQUIP_ITEM_FROM_INVENTORY'
export const UNEQUIP_ITEM_TO_INVENTORY = 'UNEQUIP_ITEM_TO_INVENTORY'


